name: .NET + Pack + Push no NuGet

on:
  release:
    types: [published]    

jobs:
  pack-push:
    env:
      CAMINHO_PROJETO: ./ZanellaNugets.sln

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:
    - uses: actions/checkout@v3
  
    - name: Exit if not on version tags
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: exit -1

    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        source-url: https://nuget.pkg.github.com/JulianoZanella/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Geração do package
      run: dotnet pack ${{ env.CAMINHO_PROJETO }} -p:GeneratePackageOnBuild=false -c Release -o out

    - name: Push no NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --skip-duplicate --no-symbols true
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
